# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_monthjournal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthjournal',
            old_name='the_month_date',
            new_name='date',
        ),
    ]
